name: Create Release

on:
  push:
    tags:
      - 'v*' # Se activa con tags como v1.0, v1.0.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Silencia el warning de Node.js
    permissions:
      contents: write # Necesita permisos para crear releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package plugin for release
        id: package
        run: |
          ZIP_NAME="dynamic_panelzoom.koplugin.zip"
          # Usa git archive para empaquetar directamente lo comiteado,
          # metiéndolo todo dentro de una carpeta llamada 'dynamic_panelzoom.koplugin/'
          git archive --format=zip --prefix=dynamic_panelzoom.koplugin/ -o $ZIP_NAME HEAD
          
          # Guardamos el nombre del zip para el siguiente paso
          echo "zip_name=${ZIP_NAME}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ${{ steps.package.outputs.zip_name }}
